import type { Metadata } from "next";
import { Signika_Negative } from 'next/font/google';

import "./globals.css";

import Header from "../components/Header";

const myFont  = Signika_Negative ({
  subsets: ['latin'],
  weight: ['400', '500', '600', '700'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }:Readonly<{children: React.ReactNode;}>) {
  return (
    <html lang="en" className={myFont.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
